// Generate src/theme.css from the registry's delego-theme cssVars, so the preview
// uses the EXACT tokens the registry ships — no hand-maintained copy to drift.
import { readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

const here = dirname(fileURLToPath(import.meta.url))
const registry = JSON.parse(
  readFileSync(resolve(here, "../../../registry.json"), "utf8")
)
const theme = registry.items.find((i) => i.name === "delego-theme")
if (!theme) throw new Error("delego-theme item not found in registry.json")

const block = (obj) =>
  Object.entries(obj)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n")

const css = `/* GENERATED by scripts/gen-theme.mjs from ../../registry.json — do not edit. */
:root {
${block({ ...theme.cssVars.theme, ...theme.cssVars.light })}
}

.dark {
${block(theme.cssVars.dark)}
}
`

writeFileSync(resolve(here, "../src/theme.css"), css)
console.log("wrote src/theme.css")
